versions:
  v0.10.1:
    entrypoints:
      train:
        image_url: #TODO
        aws_batch:
          job_definition: decode_train_0_10_1
          hardware:
            MEMORY: 8000
            VCPU: 4
            GPU: 1
          timeout: 18000
        params:
          required:
            # id: cmd_arg
            param_path: param_path
            calib_path: calib_path
          optional:
      fit:
        image_url: #TODO
        aws_batch:
          job_definition: decode_fit_0_10_1
          hardware:
            MEMORY: 8000
            VCPU: 4
            GPU: 1
          timeout: 3000
        params:
          required:
            emitter_path:
            frame_path:
            frame_meta_path:
          optional:
