versions:
  latest:
    entrypoints:
      train:
        image_url: placeholder  #TODO
        command: "python -m cli.train --config-dir=/data/config --config-name=config"  # TODO: override output folder
        aws_batch:
          job_definition: decode_train_latest
          hardware:
            MEMORY: 8000
            VCPU: 4
            GPU: 1
          timeout: 18000
        params:
          config_id: /data/config
          data_ids: /data/data
      fit:
        image_url: placeholder  #TODO
        command: #TODO
        aws_batch:
          job_definition: decode_fit_latest
          hardware:
            MEMORY: 8000
            VCPU: 4
            GPU: 1
          timeout: 3000
        params:
